import type { Metadata } from "next";
import { auth } from "@/auth"
import React from "react";
import {NavigationBar} from "@/components/NavigationBar";

const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    const session = await auth()

    return (
        <>
            <NavigationBar user={session?.user}/>
            {children}
        </>
    );
}
